# generated by datamodel-codegen:
#   filename:  essences.json
#   version:   0.28.5

from __future__ import annotations

from typing import Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Type(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    is_corruption_only: bool
    tier: int


class EssenceMods(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    Amulet: Optional[str] = None
    Belt: Optional[str] = None
    Body_Armour: Optional[str] = Field(None, alias="Body Armour")
    Boots: Optional[str] = None
    Bow: Optional[str] = None
    Claw: Optional[str] = None
    Dagger: Optional[str] = None
    Gloves: Optional[str] = None
    Helmet: Optional[str] = None
    One_Hand_Axe: Optional[str] = Field(None, alias="One Hand Axe")
    One_Hand_Mace: Optional[str] = Field(None, alias="One Hand Mace")
    One_Hand_Sword: Optional[str] = Field(None, alias="One Hand Sword")
    Quiver: Optional[str] = None
    Ring: Optional[str] = None
    Sceptre: Optional[str] = None
    Shield: Optional[str] = None
    Staff: Optional[str] = None
    Thrusting_One_Hand_Sword: Optional[str] = Field(None, alias="Thrusting One Hand Sword")
    Two_Hand_Axe: Optional[str] = Field(None, alias="Two Hand Axe")
    Two_Hand_Mace: Optional[str] = Field(None, alias="Two Hand Mace")
    Two_Hand_Sword: Optional[str] = Field(None, alias="Two Hand Sword")
    Wand: Optional[str] = None


class EssenceDisplayMods(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    Amulet: Optional[str] = None
    Armour: Optional[str] = None
    Belt: Optional[str] = None
    BodyArmour: Optional[str] = None
    Boots: Optional[str] = None
    Bow: Optional[str] = None
    Gloves: Optional[str] = None
    Helmet: Optional[str] = None
    Items: Optional[str] = None
    Jewellery: Optional[str] = None
    MeleeWeapon: Optional[str] = None
    OneHandWeapon: Optional[str] = None
    Quiver: Optional[str] = None
    RangedWeapon: Optional[str] = None
    Ring: Optional[str] = None
    Shield: Optional[str] = None
    TwoHandMeleeWeapon: Optional[str] = None
    TwoHandWeapon: Optional[str] = None
    Wand: Optional[str] = None
    Weapon: Optional[str] = None


class EssenceDisplayLine(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    category: str
    label: str
    mod: str


class Essence(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    display_blocks: Optional[List[List[EssenceDisplayLine]]] = None
    display_mods: Optional[EssenceDisplayMods] = None
    item_level_restriction: Optional[int] = None
    level: int
    level_restriction_text: Optional[str] = None
    mods: Optional[EssenceMods] = None
    name: str
    spawn_level_min: int
    type: Type


class EssencesSchema(RootModel[Optional[Dict[str, Essence]]]):
    root: Optional[Dict[str, Essence]] = None


class Model(RootModel[EssencesSchema]):
    root: EssencesSchema
